# Generated by Django 3.1.7 on 2021-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210404_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новость', max_length=50, verbose_name='Название')),
                ('anons', models.CharField(default='Анонс', max_length=250, verbose_name='Анонс')),
                ('slug', models.SlugField(default='evgsiwmoqviarskz', max_length=255, unique=True, verbose_name='URL')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.DeleteModel(
            name='Artiсles',
        ),
    ]
